site:
  url: http://chn.cloud/
users:
  friend: friend
  word: 5C014704D487CA8BB3433C5EE0D0E02FAD6B932930F22D90CDB7F90F7FA94BA8
server:
  port: 8080
  servlet:
    session:
      tracking-modes: 'cookie'

spring:
  application:
    name: urlchain
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 1200000
      max-lifetime: 2400000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.hbm2ddl.auto: validate
  profiles:
    active: local
