site:
  url: http://pruned.one/
users:
  friend: friend
  word: 5C014704D487CA8BB3433C5EE0D0E02FAD6B932930F22D90CDB7F90F7FA94BA8
server:
  port: 8080
  servlet:
    session:
      tracking-modes: 'cookie'
notification:
  telegram:
    token: 123456789012345678901234567890
    chat: 987654321
  mail:
    admin: admin@pruned.one
    subject: pruned info
email:
  smtp:
    user: info
    from: info@pruned.one
    password: examplepass
    host: smtp.pruned.one
    port: 587
    auth: true
    tls:
      enable: true

spring:
  application:
    name: prunedone
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 1200000
      max-lifetime: 2400000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.hbm2ddl.auto: validate
  profiles:
    active: local
